const actionTypes = {
  GET_HOME: "GET_HOME",
  SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
  SET_CUR_SONG_DATA: "SET_CUR_SONG_DATA",
  SET_CUR_ALBUM_ID: "SET_CUR_ALBUM_ID",
  SET_RECENT: "SET_RECENT",
  PLAY: "PLAY",
  LOADING: "LOADING",
  SET_ALBUM: "SET_ALBUM",
  PLAYLIST: "PLAYLIST",
  SEARCH: "SEARCH",
  ZERO_SCROLLTOP: "ZERO_SCROLLTOP",
  CURRENT_WIDTH: "CURRENT_WIDTH",
  SET_FOLLOW_ARTIST: " SET_FOLLOW_ARTIST",
  REMOVE_FOLLOW_ARTIST: " REMOVE_FOLLOW_ARTIST",
};
export default actionTypes;
